### ISSUE TITLE
How to use examples?

### ISSUE THREAD

**Issue by EarlGlynn** [wnd-charm/wnd-charm#45]
I've been able to compile and install everything (I think).  The command-line wndchrm gives some lengthy help info.

Perhaps I missed it, but how should the files in the examples directory be used?  I can run the various scripts (e.g., ./real_time_classifier.py or ./classifier_fit_on_fit.py) but I get a message "ImportError: No module named wndcharm.FeatureSet.  Did I miss something in the setup?

Is there one easy working example of seeing an image and the features created from that image?

Thanks for any feedback on this.

**Comment by colettace** [comment]
Hi Earl,
Sorry for the confusion. There are two versions of WND-CHARM that come with this repository. One is the command line which seems to work for you, the other is the Python API. What is not explicit in the instructions (and it should be) is that the /examples directory used the Python API. Try running <code>python setup.py install</code> in the top level directory and rerunning the example code again. Let us know if that works for you. Thanks for trying!

**Comment by EarlGlynn** [comment]
Thanks for your feedback, colettace.

Your compilation instructions work OK, but the example scripts seem to need additional arguments, e.g.,

[432 efg localhost 2015-02-07 20:53:39 /home/efg/Software/wnd-charm-master/examples]
./continuous_classification.py
wndcharm 0.2
usage: continuous_classification.py [-h] [-n <integer>] [-b <integer>]
                                    [-D [<optional path>]]
                                    classifier_file_path [output_filepath]
continuous_classification.py: error: too few arguments

So, I'm still note clear how to use the example scripts. 

I'd try to run the scripts in wnd-charm-master/tests/pywndcharm_tests, but they don't seem to have the write permissions set.  Do I just set the execute bits and run them?  I'm still very fuzzy about the examples.

The c_elegans_terminal_bulb.html file in that directory is interesting.  That provided some expected output from the program, which is very useful for a beginner.

I have made one huge run with wndchrm (30K training images in 121 classes), and I kinda understand what is going on.  Firefox seems to choke on the huge html output file (302 MB), but I transferred it to Windows and Chrome works fine with it there. 

Does Phylip show any annotations on the nodes?  My diagram looks interesting (and plausible) but none of the nodes have labels.i

What does the w classifier option do?  What is "wnn" vs "wnd"?  Did I miss that in one of the papers. 

Has anyone created any IPython notebooks to show how to use in Python?  Some actual working examples of using wnchrm would help novices get started.

wndchrm seems to be used mostly as a classifier, but have many used the program to get the image features for supervised data, and then use other machine learning approaches (random forests, SVM, etc.) for classification?

**Comment by colettace** [comment]
Earl, sorry for the delay in getting back to you. We are on the cusp of some major API changes, in the next few weeks. That's why I'd suggest not spending too much time in the current "master" branch, but instead look at what will become to new WND-CHARM Python API version 1.0, which is in this branch: https://github.com/colettace/wnd-charm/tree/tiling

Version 1.0 has a much simpler API, and more functionality. For more info on the status of the transition and to give feedback on things like the names of objects and methods, here is the current pull request: https://github.com/wnd-charm/wnd-charm/pull/44

I suggest checking out the code in that branch and looking in the /tests/pywndcharm_tests directory, where you'll see how all almost every method we have is called. The /examples directory in that branch has not been updated yet, but I'll get to that in the next day or so. IPython notebooks are on the way too.

As for using other machine learning approaches with CHARM features, by all means, please do. We do it here in the lab all the time :-)

**Comment by joelwschwartz** [comment]
Chris

I am also running into similar issue described by Earl.  Earl is a buddy of mine from way back, and I would like to include him on this thread. I have been able to setup the package, and I have even been able to generate classifiers on the commnad line, but I am stuck.  i have two questions: 
1. How can you extract the features into a csv file (or something similar) 
2. The example "classification_Mask.py" is exactly what I want to use WND-CHRM for. But I get the following error: 

Traceback (most recent call last):
  File "/Users/joschwa31/Desktop/Analysis/PyCharm/wnd-charm/examples/classification_mask.py", line 137, in <module>
    for sample in image_iter.sample():
  File "/usr/local/lib/python2.7/site-packages/wndcharm-0.2-py2.7-macosx-10.10-x86_64.egg/wndcharm/FeatureSet.py", line 332, in sample
    yield wndcharm.ImageMatrix (original, current_x, current_y, current_x+width-1, current_y+height-1,0,0)
TypeError: __init__() takes exactly 1 argument (8 given)

Any help?

Joel

**Comment by jbudman** [comment]
Hi All,

I am getting the exact same error as Joel. Having dug pretty deep into the main wndcharm.py script it seems like the ImageMatrix class has a missing constructor. Any help from the authors would be highly appreciated!

Josh

**Comment by thbaumbach** [comment]
It looks like some of the _examples_ are still outdated?! They rely on the now replaced `FeatureSet` module (namely `classifier_cross_validation.py` & `num_feature_variation_analysis.py`). And `classification_mask.py`wants to use `SampleImageTiles`.

Any (upcoming) updates on that?
